import type { PerfiladorSchema } from '../types/perfilador'

/** Fallback schema so the wizard renders when the API is not ready yet. */
export const FALLBACK_PERFILADOR_SCHEMA: PerfiladorSchema = {
  steps: [
    {
      id: 1,
      key: 'presupuesto_ubicacion',
      title: 'Encuentra tu hogar ideal',
      subtitle: 'Cuéntanos sobre tu presupuesto y ubicación preferida',
      fields: [
        {
          key: 'presupuesto',
          type: 'range',
          label: '¿Cuál es tu presupuesto de inversión?',
          min: 100_000_000,
          max: 500_000_000,
          step: 10_000_000,
          unit: 'COP',
          format: 'currency',
          default: [200_000_000, 350_000_000],
        },
        {
          key: 'vis',
          type: 'toggle',
          label: '¿Te interesa aplicar a subsidios de vivienda (VIS)?',
          on_label: 'SÍ',
          off_label: 'NO',
          default: true,
        },
        {
          key: 'ciudad',
          type: 'select',
          label: '¿En qué ciudad te gustaría comprar?',
          placeholder: 'Selecciona una ciudad',
          default: 'bogota',
          options: [
            { id: 'bogota', label: 'Bogotá' },
            { id: 'medellin', label: 'Medellín' },
            { id: 'barranquilla', label: 'Barranquilla' },
            { id: 'cartagena', label: 'Cartagena' },
          ],
        },
        {
          key: 'zona',
          type: 'chips',
          label: 'Selecciona tus zonas de preferencia:',
          multiple: true,
          depends_on: 'ciudad',
          default: ['norte'],
          options: [
            { id: 'norte', label: 'Norte', ciudad_id: 'bogota' },
            { id: 'sur', label: 'Sur', ciudad_id: 'bogota' },
            { id: 'sabana', label: 'Sabana', ciudad_id: 'bogota' },
            { id: 'occidente', label: 'Occidente', ciudad_id: 'bogota' },
            { id: 'centro', label: 'Centro', ciudad_id: 'bogota' },
            { id: 'el-poblado', label: 'El Poblado', ciudad_id: 'medellin' },
            { id: 'laureles', label: 'Laureles', ciudad_id: 'medellin' },
            { id: 'norte-baq', label: 'Norte', ciudad_id: 'barranquilla' },
            { id: 'bocagrande', label: 'Bocagrande', ciudad_id: 'cartagena' },
          ],
        },
      ],
    },
    {
      id: 2,
      key: 'caracteristicas',
      title: 'Personaliza tus preferencias',
      subtitle: 'Dinos qué buscas en la distribución y amenidades de tu nuevo hogar',
      fields: [
        {
          key: 'tipo',
          type: 'chips',
          label: 'Tipo',
          multiple: false,
          default: ['apartamento'],
          options: [
            { id: 'apartamento', label: 'Apartamento' },
            { id: 'casa', label: 'Casa' },
            { id: 'oficina', label: 'Oficina' },
            { id: 'renta-corta', label: 'Renta corta' },
          ],
        },
        {
          key: 'hab',
          type: 'chips',
          label: 'Habitaciones',
          multiple: false,
          default: ['2'],
          options: [
            { id: '1', label: '1' },
            { id: '2', label: '2' },
            { id: '3', label: '3' },
            { id: '4+', label: '4+' },
          ],
        },
        {
          key: 'area',
          type: 'chips',
          label: 'Área aproximada',
          multiple: false,
          default: ['80-120'],
          options: [
            { id: '40-80', label: '40-80m²' },
            { id: '80-120', label: '80-120m²' },
            { id: '120-180', label: '120-180m²' },
            { id: '180+', label: '180m²+' },
          ],
        },
        {
          key: 'parqueaderos',
          type: 'chips',
          label: 'Parqueaderos',
          multiple: false,
          default: ['2'],
          options: [
            { id: '0', label: '0' },
            { id: '1', label: '1' },
            { id: '2', label: '2' },
            { id: '3+', label: '3+' },
          ],
        },
        {
          key: 'amenities',
          type: 'amenity_grid',
          label: 'Amenidades',
          default: ['piscina', 'gimnasio'],
          options: [
            { id: 'piscina', label: 'Piscina' },
            { id: 'gimnasio', label: 'Gimnasio' },
            { id: 'coworking', label: 'Coworking' },
            { id: 'pet-friendly', label: 'Pet friendly' },
            { id: 'zonas-verdes', label: 'Zonas verdes' },
            { id: 'seguridad', label: 'Seguridad 24/7' },
            { id: 'bbq', label: 'Zona BBQ' },
            { id: 'salon', label: 'Salón social' },
          ],
        },
        {
          key: 'etapa',
          type: 'chips',
          label: 'Etapa del proyecto',
          multiple: false,
          default: ['entrega'],
          options: [
            { id: 'entrega', label: 'Entrega inmediata' },
            { id: 'construccion', label: 'En construcción' },
            { id: 'sobreplanos', label: 'Sobre planos' },
          ],
        },
      ],
    },
    {
      id: 3,
      key: 'resultados',
      title: '¡Estos lugares son perfectos para ti!',
      subtitle:
        'Seleccionamos las mejores opciones según tus preferencias — conócelos y elige tu favorito.',
      fields: [],
    },
  ],
  copy: {
    banner_title: 'Tenemos el lugar perfecto para ti',
    banner_text:
      'Responde unas preguntas y te mostraremos los proyectos que mejor se adaptan a lo que buscas.',
    continue_label: 'Continuar',
    back_label: 'Volver',
    results_title: '¡Estos lugares son perfectos para ti!',
    results_empty: 'Ajusta tus filtros para ver más proyectos.',
    counter_label: '{n} proyectos disponibles según tus preferencias',
    lead_title: 'Guarda tus recomendaciones',
    lead_text: 'Recibe alertas de nuevos proyectos que coincidan con tu perfil.',
    lead_submit: 'Enviar',
    lead_whatsapp: 'Escribir por WhatsApp',
    download_pdf: 'Descargar PDF',
    favorite_label: 'Guardar favorito',
    match_label: 'match!',
    preferences_title: 'Tus preferencias',
  },
}
